obstacle_range: 6.0
raytrace_range: 8.5
footprint: [[0.35,0.25],[0.35,-0.25],[-0.35,-0.25],[-0.35,0.25]]
map_topic: /map
subscribe_to_update: true
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: hokuyo,data_type: LaserScan, topic: /scan,marking: true , clearing: true }
global_frame: map
robot_base_frame: base_link
always_send_full_costmap: true
